/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Driver {
  'userData' : User,
  'isSharingLocation' : boolean,
  'busNumber' : string,
  'currentLocation' : [] | [Location],
}
export interface Location {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : Time,
}
export type LocationUpdateStatus = { 'inactive' : null } |
  { 'notFound' : null } |
  { 'success' : null };
export type RegistrationStatus = { 'failure' : string } |
  { 'success' : null };
export type Time = bigint;
export interface User {
  'id' : Principal,
  'status' : UserStatus,
  'name' : string,
  'role' : UserRole,
}
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'busNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'inactive' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateUser' : ActorMethod<[Principal], undefined>,
  'adminRegister' : ActorMethod<[string], RegistrationStatus>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateUser' : ActorMethod<[Principal], undefined>,
  'driverRegister' : ActorMethod<[string], RegistrationStatus>,
  'getAllDrivers' : ActorMethod<[], Array<Driver>>,
  'getAllTravellers' : ActorMethod<[], Array<User>>,
  'getBusLocation' : ActorMethod<[string], [] | [Location]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDriver' : ActorMethod<[string], [] | [Driver]>,
  'getLocation' : ActorMethod<[string], [] | [Location]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleLocationSharing' : ActorMethod<[string], boolean>,
  'travellerRegister' : ActorMethod<[], RegistrationStatus>,
  'updateLocation' : ActorMethod<[string, Location], LocationUpdateStatus>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];