/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RegistrationStatus = IDL.Variant({
  'failure' : IDL.Text,
  'success' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'status' : UserStatus,
  'name' : IDL.Text,
  'role' : UserRole,
});
export const Time = IDL.Int;
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
});
export const Driver = IDL.Record({
  'userData' : User,
  'isSharingLocation' : IDL.Bool,
  'busNumber' : IDL.Text,
  'currentLocation' : IDL.Opt(Location),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'busNumber' : IDL.Opt(IDL.Text),
});
export const LocationUpdateStatus = IDL.Variant({
  'inactive' : IDL.Null,
  'notFound' : IDL.Null,
  'success' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateUser' : IDL.Func([IDL.Principal], [], []),
  'adminRegister' : IDL.Func([IDL.Text, IDL.Text], [RegistrationStatus], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateUser' : IDL.Func([IDL.Principal], [], []),
  'driverRegister' : IDL.Func([IDL.Text, IDL.Text], [RegistrationStatus], []),
  'getAllDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'getAllTravellers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getBusLocation' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDriver' : IDL.Func([IDL.Text], [IDL.Opt(Driver)], ['query']),
  'getLocation' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleLocationSharing' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'travellerRegister' : IDL.Func([IDL.Text], [RegistrationStatus], []),
  'updateLocation' : IDL.Func([IDL.Text, Location], [LocationUpdateStatus], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RegistrationStatus = IDL.Variant({
    'failure' : IDL.Text,
    'success' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'status' : UserStatus,
    'name' : IDL.Text,
    'role' : UserRole,
  });
  const Time = IDL.Int;
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
  });
  const Driver = IDL.Record({
    'userData' : User,
    'isSharingLocation' : IDL.Bool,
    'busNumber' : IDL.Text,
    'currentLocation' : IDL.Opt(Location),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'busNumber' : IDL.Opt(IDL.Text),
  });
  const LocationUpdateStatus = IDL.Variant({
    'inactive' : IDL.Null,
    'notFound' : IDL.Null,
    'success' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateUser' : IDL.Func([IDL.Principal], [], []),
    'adminRegister' : IDL.Func([IDL.Text, IDL.Text], [RegistrationStatus], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateUser' : IDL.Func([IDL.Principal], [], []),
    'driverRegister' : IDL.Func([IDL.Text, IDL.Text], [RegistrationStatus], []),
    'getAllDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'getAllTravellers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getBusLocation' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDriver' : IDL.Func([IDL.Text], [IDL.Opt(Driver)], ['query']),
    'getLocation' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleLocationSharing' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'travellerRegister' : IDL.Func([IDL.Text], [RegistrationStatus], []),
    'updateLocation' : IDL.Func(
        [IDL.Text, Location],
        [LocationUpdateStatus],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };